name: GriefPreventionClaimRestrict
version: 1.0
main: pw.ollie.gpclaimrestrict.GPCRPlugin

depend: [GriefPrevention]

permissions:
  gpcr.bypass:
    description: Bypass claim restrictions
  gpcr.trust:
    description: Allows trusting and untrusting players

commands:
  trustnear:
    description: Trust a player to build near your claims
  untrustnear:
    description: Stop trusting a player to build near your claims
